export const APP_ROUTES = {
  home: '/',
  access: '/portal',
  workspace: '/workspace',
  archive: '/archive',
  monitor: '/monitor',
  overview: '/overview',
  insights: '/insights',
  insightsMap: '/insights/map',
  control: '/control',
  controlActivity: '/control/activity',
  reportsRegional: '/reports/regional',
} as const;

export const LEGACY_ROUTE_REDIRECTS = [
  { from: '/login', to: APP_ROUTES.access },
  { from: '/captures', to: APP_ROUTES.workspace },
  { from: '/captures/history', to: APP_ROUTES.archive },
  { from: '/region', to: APP_ROUTES.monitor },
  { from: '/admin', to: APP_ROUTES.overview },
  { from: '/director', to: APP_ROUTES.insights },
  { from: '/director/map', to: APP_ROUTES.insightsMap },
  { from: '/superadmin', to: APP_ROUTES.control },
  { from: '/superadmin/audit', to: APP_ROUTES.controlActivity },
  { from: '/plantilla-vehicular', to: APP_ROUTES.overview },
  { from: '/director-general', to: APP_ROUTES.insights },
  { from: '/director-general/map', to: APP_ROUTES.insightsMap },
  { from: '/director-operativo', to: APP_ROUTES.monitor },
  { from: '/coordinacion', to: APP_ROUTES.control },
  { from: '/coordinacion/audit', to: APP_ROUTES.controlActivity },
  { from: '/reports', to: APP_ROUTES.reportsRegional },
] as const;
